apiVersion: v1
kind: Service
metadata:
  name: spring-boot-app-service
  labels:
    app: spring-boot-app
spec:
  type: LoadBalancer

  ports:
    - port: 80
      targetPort: 8010

  selector:
    app: spring-boot-app